"""DSPy module for AI-powered Pull Request code review."""

from __future__ import annotations

from dataclasses import dataclass

import dspy

from osstriage.core.exceptions import AIModuleError
from osstriage.core.logging import get_logger
from osstriage.dspy_modules.signatures import ReviewPRSignature

logger = get_logger("review_pr")


@dataclass(frozen=True, slots=True)
class PRReviewResult:
    """Structured output from a Pull Request review.

    Attributes:
        security_risks: Identified security concerns with suggested fixes.
        performance_issues: Performance-related findings.
        logic_flaws: Logical errors, bugs, or missing edge cases.
        suggestions: General code quality improvement suggestions.
        overall_assessment: Summary verdict (APPROVE / REQUEST_CHANGES / COMMENT).
    """

    security_risks: str
    performance_issues: str
    logic_flaws: str
    suggestions: str
    overall_assessment: str

    @property
    def verdict(self) -> str:
        """Extract the verdict keyword from the overall assessment."""
        text = self.overall_assessment.upper()
        for v in ("REQUEST_CHANGES", "APPROVE", "COMMENT"):
            if v in text:
                return v
        return "COMMENT"

    def to_markdown(self) -> str:
        """Render the review as a Markdown comment suitable for GitHub."""
        sections = [
            ("🔒 Security Risks", self.security_risks),
            ("⚡ Performance Issues", self.performance_issues),
            ("🐛 Logic Flaws", self.logic_flaws),
            ("💡 Suggestions", self.suggestions),
            ("📋 Overall Assessment", self.overall_assessment),
        ]
        parts = ["## 🤖 OSSTriage — Automated PR Review\n"]
        for heading, body in sections:
            parts.append(f"### {heading}\n\n{body}\n")
        parts.append(
            "\n---\n*Generated by [OSSTriage](https://github.com/your-org/osstriage) — "
            "AI-driven code review for OSS maintainers.*"
        )
        return "\n".join(parts)


class ReviewPRModule(dspy.Module):
    """DSPy module that analyses a PR diff and produces structured feedback.

    Uses ``dspy.ChainOfThought`` for step-by-step reasoning about the
    code changes before producing the final output fields.
    """

    def __init__(self) -> None:
        super().__init__()
        self.reviewer = dspy.ChainOfThought(ReviewPRSignature)

    def forward(
        self,
        diff: str,
        pr_title: str = "",
        pr_body: str = "",
    ) -> PRReviewResult:
        """Run the review pipeline.

        Args:
            diff: Unified diff string of the PR.
            pr_title: Title of the PR.
            pr_body: Description body of the PR.

        Returns:
            A :class:`PRReviewResult` with categorised feedback.

        Raises:
            AIModuleError: If the underlying LLM call fails.
        """
        try:
            logger.info("Running PR review (diff length: %d chars)", len(diff))
            result = self.reviewer(
                diff=diff,
                pr_title=pr_title,
                pr_body=pr_body,
            )
            return PRReviewResult(
                security_risks=result.security_risks,
                performance_issues=result.performance_issues,
                logic_flaws=result.logic_flaws,
                suggestions=result.suggestions,
                overall_assessment=result.overall_assessment,
            )
        except Exception as exc:
            raise AIModuleError(
                f"PR review module failed: {exc}", cause=exc
            ) from exc
