"""DSPy module for AI-powered GitHub Issue triaging."""

from __future__ import annotations

from dataclasses import dataclass, field

import dspy

from osstriage.core.exceptions import AIModuleError
from osstriage.core.logging import get_logger
from osstriage.dspy_modules.signatures import TriageIssueSignature

logger = get_logger("triage_issue")


@dataclass(frozen=True, slots=True)
class IssueTriageResult:
    """Structured output from issue triage.

    Attributes:
        suggested_labels: Labels the AI recommends applying.
        priority_score: Numeric priority (1–5) with justification.
        summary: Concise summary of the issue.
        suggested_assignee_expertise: Expertise area for the ideal assignee.
    """

    suggested_labels: list[str]
    priority_score: str
    summary: str
    suggested_assignee_expertise: str

    @property
    def priority_numeric(self) -> int:
        """Extract the numeric priority value (defaults to 3 if unparseable)."""
        for ch in self.priority_score:
            if ch.isdigit():
                val = int(ch)
                if 1 <= val <= 5:
                    return val
        return 3

    def to_markdown(self) -> str:
        """Render the triage result as a Markdown comment."""
        labels_str = ", ".join(f"`{lbl}`" for lbl in self.suggested_labels)
        priority_emoji = {1: "🟢", 2: "🔵", 3: "🟡", 4: "🟠", 5: "🔴"}
        emoji = priority_emoji.get(self.priority_numeric, "⚪")

        parts = [
            "## 🤖 OSSTriage — Automated Issue Triage\n",
            f"### 📋 Summary\n\n{self.summary}\n",
            f"### 🏷️ Suggested Labels\n\n{labels_str}\n",
            f"### {emoji} Priority\n\n{self.priority_score}\n",
            f"### 👤 Ideal Expertise\n\n{self.suggested_assignee_expertise}\n",
            "\n---\n*Generated by [OSSTriage](https://github.com/your-org/osstriage) — "
            "AI-driven issue triage for OSS maintainers.*",
        ]
        return "\n".join(parts)


class TriageIssueModule(dspy.Module):
    """DSPy module that triages a GitHub Issue into labels and priority.

    Uses ``dspy.ChainOfThought`` for structured reasoning before
    producing classification results.
    """

    def __init__(self) -> None:
        super().__init__()
        self.triager = dspy.ChainOfThought(TriageIssueSignature)

    def forward(
        self,
        issue_title: str,
        issue_body: str,
        existing_labels: str = "",
    ) -> IssueTriageResult:
        """Run the triage pipeline.

        Args:
            issue_title: Title of the GitHub Issue.
            issue_body: Full body text of the Issue.
            existing_labels: Comma-separated existing labels (may be empty).

        Returns:
            An :class:`IssueTriageResult` with labels and priority.

        Raises:
            AIModuleError: If the underlying LLM call fails.
        """
        try:
            logger.info("Triaging issue: %s", issue_title[:80])
            result = self.triager(
                issue_title=issue_title,
                issue_body=issue_body,
                existing_labels=existing_labels,
            )
            # Parse comma-separated labels into a clean list
            labels = [
                lbl.strip().lower()
                for lbl in result.suggested_labels.split(",")
                if lbl.strip()
            ]
            return IssueTriageResult(
                suggested_labels=labels,
                priority_score=result.priority_score,
                summary=result.summary,
                suggested_assignee_expertise=result.suggested_assignee_expertise,
            )
        except Exception as exc:
            raise AIModuleError(
                f"Issue triage module failed: {exc}", cause=exc
            ) from exc
